### PR TITLE
New superpower: Hydra!

### PR DESCRIPTION
**Pull request by darabos**
It seemed like a simple idea at first, but I had to adjust the plumbing here and there.
- Make `runningCurves` a list for each player, so a player can have more than one curve.
- Instead of color, store the specific curve for drawn points. So that Hydra heads can collide properly.
- Instead of `hasJustStarted` I've added a multi-frame, per-curve immunity system. This is needed because the freshly split heads need to not collide each other for a couple frames after splitting.

I'll report back when we get to play with this a bit!

### CODE REVIEW

**Comment by maechler** [comment]
@darabos Thank you very much for your contributions! I am very sorry I did not respond earlier, I did not receive any notifications about your pull requests (for whatever reason?!). I noticed your star and fork though.
I will try to test this the next days and I would be happy to soon publish a new version with new superpowers! =)

**Comment by maechler** [comment]
@darabos These superpowers are awesome and very nicely implemented! Thank you very much for that contribution!

**Comment by darabos** [comment]
> @darabos These superpowers are awesome and very nicely implemented! Thank you very much for that contribution!

You're very kind! We've played a bit today and tried Hydra for the first time. It looks good and it's fun to trigger. But we haven't found many strategic uses. Only one that seemed effective is when you're trying to push someone into the wall you can finish them off by triggering Hydra and smashing one head into the wall in their way. But this just wins you a situation that you were already likely win.

Maybe we just need to get used to it. Whenever someone triggered it they got so distracted by the multiple heads that they often just crashed all of them. 😄

**Comment by maechler** [comment]
haha 😅
Actually I think Hydra can be a very useful superpower if you get used to it. But even if it was not very useful after all, it simply looks awesome!

I just published a new version including your contributions and some minor improvements on other parts: https://achtungkurve.com/

Thanks again very much! If you and your friends can think of more superpowers, feel free to contribute again!

**Pull request merged**
